version: '3.8'
services:
  walphle-watcher:
    restart: 'unless-stopped'
    build:
      context: ./
    env_file:
      - .env
    logging:
        driver: "json-file"
        options:
          max-size: "50m"
